name: eduit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.3
  image_picker: ^0.8.6
  flutter_custom_carousel_slider: ^1.0.0
  anim_search_bar: ^2.0.3
  persistent_bottom_nav_bar: ^5.0.2
  share_plus: ^7.2.1
  path_provider: ^2.0.14
  url_launcher: ^6.1.10
  fluttertoast: ^8.2.1
  http: ^0.13.5
  dropdown_button2: ^2.1.3
  intl: ^0.18.1
  get_secure_storage: ^1.0.4


dev_dependencies: 
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.2.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter
  
  
flutter: 
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserratt.ttf



